<x-app-layout>
    <x-slot name="header">
        <h2 class="font-black text-xl" style="color:#1a3327;">Manage Mentor Profile</h2>
    </x-slot>

    <div class="py-10">
        <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

            @if (session('status'))
                <div class="mb-6 px-5 py-3 rounded-xl text-sm font-medium" style="background:rgba(196,154,60,.1); border:1px solid rgba(196,154,60,.3); color:#8a6a1a;">
                    {{ session('status') }}
                </div>
            @endif

            <form method="POST" action="{{ route('mentor.profile.update') }}"
                  class="rounded-2xl p-8 space-y-8" style="background:white; border:1px solid #e6e0d0;">
                @csrf
                @method('PUT')

                {{-- Expertise / skills --}}
                <div>
                    <label class="block text-sm font-semibold mb-2" style="color:#1a3327;">
                        Expertise <span class="font-normal" style="color:#6b7a72;">(comma-separated skills)</span>
                    </label>
                    <input type="text"
                           name="expertise_raw"
                           id="expertise_raw"
                           value="{{ old('expertise_raw', implode(', ', $profile->expertise ?? [])) }}"
                           placeholder="e.g. PHP, Laravel, System Design"
                           class="w-full rounded-xl px-4 py-2.5 text-sm transition @error('expertise') border-red-400 @enderror"
                           style="border:1px solid #d6cfbe; color:#1a3327;"
                           onfocus="this.style.borderColor='#1a3327'" onblur="this.style.borderColor='#d6cfbe'" />
                    {{-- Hidden expertise[] inputs are generated by JS from the raw input --}}
                    <div id="expertise-hidden"></div>
                    @error('expertise')
                        <p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                    <p class="mt-1.5 text-xs text-gray-400">Separate each skill with a comma.</p>
                </div>

                {{-- Availability --}}
                <div>
                    <label class="block text-sm font-semibold mb-2" style="color:#1a3327;">Availability</label>
                    <div class="flex gap-4">
                        @foreach (['open' => 'Open to mentoring', 'closed' => 'Not available'] as $val => $label)
                            <label class="flex items-center gap-2 cursor-pointer">
                                <input type="radio" name="availability" value="{{ $val }}"
                                       {{ old('availability', $profile->availability) === $val ? 'checked' : '' }}
                                       style="accent-color:#1a3327;" />
                                <span class="text-sm" style="color:#4a5e55;">{{ $label }}</span>
                            </label>
                        @endforeach
                    </div>
                    @error('availability')
                        <p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                {{-- Session type --}}
                <div>
                    <label class="block text-sm font-semibold mb-2" style="color:#1a3327;">Session Type</label>
                    <div class="flex flex-wrap gap-4">
                        @foreach (['free' => 'Free', 'paid' => 'Paid', 'project_based' => 'Project-based'] as $val => $label)
                            <label class="flex items-center gap-2 cursor-pointer">
                                <input type="radio" name="session_type" value="{{ $val }}"
                                       id="session_type_{{ $val }}"
                                       {{ old('session_type', $profile->session_type) === $val ? 'checked' : '' }}
                                       style="accent-color:#1a3327;" />
                                <span class="text-sm" style="color:#4a5e55;">{{ $label }}</span>
                            </label>
                        @endforeach
                    </div>
                    @error('session_type')
                        <p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                {{-- Hourly rate (shown only when session_type = paid) --}}
                <div id="hourly-rate-field" class="{{ old('session_type', $profile->session_type) === 'paid' ? '' : 'hidden' }}">
                    <label for="hourly_rate" class="block text-sm font-semibold mb-2" style="color:#1a3327;">Hourly Rate (₦)</label>
                    <div class="relative w-48">
                        <span class="absolute inset-y-0 left-3 flex items-center text-sm" style="color:#6b7a72;">₦</span>
                        <input type="number" name="hourly_rate" id="hourly_rate" min="0" max="9999999" step="1"
                               value="{{ old('hourly_rate', $profile->hourly_rate) }}"
                               class="w-full pl-7 pr-4 py-2.5 rounded-xl text-sm transition @error('hourly_rate') border-red-400 @enderror"
                               style="border:1px solid #d6cfbe; color:#1a3327;"
                               onfocus="this.style.borderColor='#1a3327'" onblur="this.style.borderColor='#d6cfbe'" />
                    </div>
                    @error('hourly_rate')
                        <p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                {{-- Years of experience --}}
                <div>
                    <label for="years_of_experience" class="block text-sm font-semibold mb-2" style="color:#1a3327;">Years of Experience</label>
                    <input type="number" name="years_of_experience" id="years_of_experience"
                           min="0" max="50" step="1"
                           value="{{ old('years_of_experience', $profile->years_of_experience) }}"
                           class="w-32 rounded-xl px-4 py-2.5 text-sm transition @error('years_of_experience') border-red-400 @enderror"
                           style="border:1px solid #d6cfbe; color:#1a3327;"
                           onfocus="this.style.borderColor='#1a3327'" onblur="this.style.borderColor='#d6cfbe'" />
                    @error('years_of_experience')
                        <p class="mt-1.5 text-xs text-red-600">{{ $message }}</p>
                    @enderror
                </div>

                <div class="flex items-center justify-end pt-2" style="border-top:1px solid #e6e0d0;">
                    <button type="submit"
                            class="px-6 py-2.5 rounded-xl text-sm font-bold transition"
                            style="background:#1a3327; color:#f4f1e8;"
                            onmouseover="this.style.background='#0f2219'" onmouseout="this.style.background='#1a3327'">
                        Save Profile
                    </button>
                </div>
            </form>
        </div>
    </div>

    <script>
        // Convert comma-separated expertise to hidden inputs on submit
        document.querySelector('form').addEventListener('submit', function () {
            const raw = document.getElementById('expertise_raw').value;
            const container = document.getElementById('expertise-hidden');
            container.innerHTML = '';
            raw.split(',')
               .map(s => s.trim())
               .filter(s => s !== '')
               .forEach(skill => {
                   const input = document.createElement('input');
                   input.type  = 'hidden';
                   input.name  = 'expertise[]';
                   input.value = skill;
                   container.appendChild(input);
               });
        });

        // Show/hide hourly rate field based on session type selection
        document.querySelectorAll('input[name="session_type"]').forEach(function (radio) {
            radio.addEventListener('change', function () {
                document.getElementById('hourly-rate-field').classList.toggle('hidden', this.value !== 'paid');
            });
        });
    </script>
</x-app-layout>
